// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package your.basepackage.name.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface OslcDomainConstants
{
    // Start of user code user constants
    // End of user code

    /**
     * @deprecated use {@link OslcDomainConstants#OSLC_CORE_NAMSPACE} or {@link OslcDomainConstants#OSLC_CORE_DOMAIN_NAME} instead
     */
    @Deprecated(since = "5.0.1")
    public static String OSLC_CORE_DOMAIN = "http://open-services.net/ns/core#";
    public static String OSLC_CORE_DOMAIN_NAME = "OSLC Core";
    public static String OSLC_CORE_NAMSPACE = "http://open-services.net/ns/core#"; //Vocabulary namespace for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined 
    public static String OSLC_CORE_NAMSPACE_PREFIX = "oslc"; //Vocabulary prefix for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined

}
