// Start of user code Copyright
/*
 * Copyright (C) 2023 Daniel Pindur <pindurdan@gmail.com>, <xpindu01@stud.fit.vutbr.cz>
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package cz.vutbr.fit.danielpindur.oslc.jira.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface FoafDomainConstants
{
    // Start of user code user constants
    // End of user code

    /**
     * @deprecated use {@link FoafDomainConstants#FOAF_NAMSPACE} or {@link FoafDomainConstants#FOAF_DOMAIN_NAME} instead
     */
    @Deprecated(since = "5.0.1")
    public static String FOAF_DOMAIN = "http://xmlns.com/foaf/0.1/";
    public static String FOAF_DOMAIN_NAME = "FOAF";
    public static String FOAF_NAMSPACE = "http://xmlns.com/foaf/0.1/"; //Vocabulary namespace for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined 
    public static String FOAF_NAMSPACE_PREFIX = "foaf"; //Vocabulary prefix for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined

    public static String PERSON_PATH = "person";  //the relative path of the resource shape URL.
    public static String PERSON_NAMESPACE = FoafDomainConstants.FOAF_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PERSON_LOCALNAME = "Person"; //localName of the rdfs:class the resource describes
    public static String PERSON_TYPE = PERSON_NAMESPACE + PERSON_LOCALNAME; //fullname of the rdfs:class the resource describes
}
