// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package your.basepackage.name.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface Oslc_rmDomainConstants
{
    // Start of user code user constants
    // End of user code

    /**
     * @deprecated use {@link Oslc_rmDomainConstants#OSLC_REQUIREMENTS_MANAGEMENT_NAMSPACE} or {@link Oslc_rmDomainConstants#OSLC_REQUIREMENTS_MANAGEMENT_DOMAIN_NAME} instead
     */
    @Deprecated(since = "5.0.1")
    public static String OSLC_REQUIREMENTS_MANAGEMENT_DOMAIN = "http://open-services.net/ns/rm#";
    public static String OSLC_REQUIREMENTS_MANAGEMENT_DOMAIN_NAME = "OSLC Requirements Management";
    public static String OSLC_REQUIREMENTS_MANAGEMENT_NAMSPACE = "http://open-services.net/ns/rm#"; //Vocabulary namespace for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined 
    public static String OSLC_REQUIREMENTS_MANAGEMENT_NAMSPACE_PREFIX = "oslc_rm"; //Vocabulary prefix for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined

    public static String REQUIREMENT_PATH = "requirement";  //the relative path of the resource shape URL.
    public static String REQUIREMENT_NAMESPACE = Oslc_rmDomainConstants.OSLC_REQUIREMENTS_MANAGEMENT_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String REQUIREMENT_LOCALNAME = "Requirement"; //localName of the rdfs:class the resource describes
    public static String REQUIREMENT_TYPE = REQUIREMENT_NAMESPACE + REQUIREMENT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String REQUIREMENTCOLLECTION_PATH = "requirementCollection";  //the relative path of the resource shape URL.
    public static String REQUIREMENTCOLLECTION_NAMESPACE = Oslc_rmDomainConstants.OSLC_REQUIREMENTS_MANAGEMENT_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String REQUIREMENTCOLLECTION_LOCALNAME = "RequirementCollection"; //localName of the rdfs:class the resource describes
    public static String REQUIREMENTCOLLECTION_TYPE = REQUIREMENTCOLLECTION_NAMESPACE + REQUIREMENTCOLLECTION_LOCALNAME; //fullname of the rdfs:class the resource describes
}
